[package]
name = "user_agent_legion"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "user_agent_legion"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }

